# 友情链接的数据文件

[meta]
type = "list"

[[item]]
name = "Rickyxrc"
url = "https://rickyxrc.cc"
description = "Frontend / Backend Developer"
avatar = "https://avatars.githubusercontent.com/u/81732554"

[[item]]
name = "汪心禾"
url = "https://wxh.im/"
description = "17 y.o. Grade 12 Student / former C++ competitive programmer / Python / ..."
avatar = "https://github.com/wxh06.png"

[[item]]
name = "Ariasakaの小窝"
url = "https://blog.yaria.top/"
description = "人有悲欢离合 月有阴晴圆缺"
avatar = "https://weavatar.com/avatar/795ce413eb6c7485954b78283ffa3e00"

[[item]]
name = "dsy4567 的小站"
url = "https://dsy4567.icu/"
description = "站长很懒，不想写网站介绍"
avatar = "https://avatars.githubusercontent.com/u/84607814"

[[item]]
name = "Fat Old Eight's Blog"
url = "https://fat-old-eight.github.io/"
description = "Tip：如何提升自己的技术，根据所有大佬的建（fu）议（du）…多练"
avatar = "https://api.yimian.xyz/img/?path=imgbed/img_bd4dcd7_210x222_8_null_normal.jpeg"

[[item]]
name = "robinyqc"
url = "https://robinyqc.cn/"
description = "中学 OIer。什么语言都不会。玩 MC。"
avatar = "https://s2.loli.net/2023/05/19/T2bkCRFYuhaDgji.png"

[[item]]
name = "六楼溜刘的小窝"
url = "https://x-six-floor-slip-liu-x.github.io/"
description = "我是超级题解王"
avatar = "https://github.com/X-six-floor-slip-liu-X.png"

[[item]]
name = "Zi_Gao 的小站"
url = "https://www.zigao.ac/"
description = "Do not go gentle into that good night."
avatar = "https://www.zigao.ac/favicon.png"

[[item]]
name = "SBGA (Unofficial)"
url = "https://sbga.cc/"
description = "试驾的马没了 o_o"
avatar = "https://s2.loli.net/2023/05/10/fjaY7iIn65VvSLX.webp"

[[item]]
name = "Walter_Fang 的博客"
url = "https://walterfang.us.kg/"
description = "Software Developer & Rhythm Game Player"
avatar = "https://cdn.luogu.com.cn/upload/usericon/609249.png"

[[item]]
name = "菲兹克斯喵"
url = "https://physnya.top"
description = "菲兹克斯喵的blog"
avatar = "https://physnya.top/img/Physics_nya.jpg"

[[item]]
name = "Meorion"
url = "https://blog.meorion.moe/"
description = "去码头整点薯条"
avatar = "https://gravatar.s22y.moe/avatar/me"

[[item]]
name = "flash"
url = "https://blog.rbkou.me"
description = "苔花如米小，也学牡丹开。"
avatar = "https://blog.rbkou.me/assets/img/avarta.png"

[[item]]
name = "smallfang"
url = "https://blog.smallfang.fun/"
description = "睡觉选手"
avatar = "http://cdn.rotriw.com/smallfang/avatar.png"
